# action.yml
name: 'Connect a May First shell account'
description: 'Connect to a May First web configuration server access shell SSH user'
inputs:
  user:  # id of input
    description: 'User'
    required: true
  password:  # id of input
    description: 'Password'
    required: true
  comment:  # id of input
    description: 'Comment'
    required: true
outputs:
  time: # id of output
    description: 'Time of connection attempt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.comment }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}

branding:
  icon: 'server'
  color: 'red'
