# action.yml
name: 'Connect'
description: 'Connect to May First shell'
inputs:
  comment:  # id of input
    description: 'Comment'
    required: true
outputs:
  time: # id of output
    description: 'Time of connection attempt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.comment }}
